### ISSUE TITLE
Support delimiter requests for container listings

### ISSUE THREAD

**Issue by tipabu** [swiftstack/ProxyFS#149]
Currently, trying to list a ProxyFS "container" through the `pfs` middleware ignores `delimiter` query params, causing all objects in the container to be listed.

This would probably be fairly cheap to do for `delimiter=/`, but the more general case still requires that we walk the whole tree. Maybe it'd be enough for 90% of use cases to support `/` and 400 any other delimiters?

Fixing this should solve several Swift and Swift3 functional tests (as well as make large volumes manageable for Swift API users).

**Comment by gerardgine** [comment]
Changes included in tag 1.5.3.1 and merged into development + stable branches.
