### ISSUE TITLE
Expose JSON-RPC interface to proxyfsd via pfs_middleware

### ISSUE THREAD

**Issue by tipabu** [swiftstack/ProxyFS#245]
This is part of the general move to expose more of ProxyFS directly to clients; see also: #229, #230, #241

Introduce a new HTTP method (`PROXYFS`?) that can be used on the volume/account to allow clients to make JsonRpcClient requests directly. Method will only be valid at the account (and only for bimodal accounts), so we can use that to look up which proxyfsd instance to talk to. Require JSON request bodies, probably with some limit on size – send it straight to proxyfsd. Emit the JSON response verbatim back to the client. If the call times out, respond `502 Bad Gateway`.

Similar to the `X-Bypass-ProxyFS` header, this should be limited to Swift owners; once we have a `bypass_mode` option, it should (as a first pass) require `read-write`.

Bonus points:
- parse requests to verify format before sending to proxyfs
- whitelist of RPC methods to allow when `bypass_mode = read-only`
- allow client to specify an RPC timeout (keeping some reasonable default if _not_ specified)
- consider allowing multiple JSON objects per request, instead of requiring pipelined HTTP requests
- consider sniffing for errors and responding 400

**Comment by edmc-ss** [comment]
I very much like PROXYFS as the method for a number of reasons:
1) It's specific to ProxyFS the technology's name today
2) It "talks" to proxyfsd ultimately
3) It's purpose is to add true "FS" features to Swift's "PROXY" :-).
I dare say I very much wish we had used this JSON-RPC tunneled thru HTTP from the get-go :-(

**Comment by edmc-ss** [comment]
BTW, for package "liveness", I wanted to do an RpcPing and found the following definitions helpful:
```
type pingReqStruct struct {
	JSONrpc string            `json:"jsonrpc"`
	Method  string            `json:"method"`
	Params  [1]jrpcfs.PingReq `json:"params"`
	ID      uint64            `json:"id"`
}

type pingReplyStruct struct {
	ID     uint64           `json:"id"`
	Result jrpcfs.PingReply `json:"result"`
	Error  string           `json:"error"`
}
```
json.{Marshal|Unmarshal}() are then used to reference the appropriate JSON-RPC API from package "jrpcfs". Of course, in "liveness", I'm only using RpcPing. For `pfsagentd`, I can use them all should we implement this new HTTP PROXYFS Method :-)

**Comment by edmc-ss** [comment]
Here's an example of the RpcPing request:
```
	pingReq.JSONrpc = "2.0"
	pingReq.Method = "Server.RpcPing"
	pingReq.Params[0].Message = "Ping at " + time.Now().Format(time.RFC3339)
	pingReq.ID = nextID // Use a 64-bit Nonce here
	pingReqBuf, err = json.Marshal(pingReq)
```
And here is the most trivial interpretation of the reply:
```
	pingReplyLen, err = tcpConn.Read(pingReplyBuf)
	pingReplyBuf = pingReplyBuf[:pingReplyLen]
	err = json.Unmarshal(pingReplyBuf, &pingReply)
```
