### ISSUE TITLE
regression_test.py is misnamed

### ISSUE THREAD

**Issue by orion** [swiftstack/ProxyFS#59]
I know this has been on the TBD list for awhile, but perhaps now is a good time to actually do it as people are starting to take a look at the project.  Probably a better presentation is a Makefile with one or more support scripts written in python.

**Comment by edmc-ss** [comment]
There is now a Makefile in the repo that is the equivalent of the misleadingly named **regression_test.py**. It has a number of build targets, but the default (`all`) is equivalent to what regression_test.py would do both in a Linux (e.g. CentOS) environment and in a cross development environment (e.g. MacOS where there is no ability to build the C submodules).

Note that the Makefile convention has also been added to the two Golang packages in the `cstruct` and `sortedmap` repos.
